export const presetPrompts: Record<string, string> = {
  "summary": "Summary (Generate a concise high-level professional summary of the content)",
  "exec_summary": "Executive Summary (Generate a concise high-level professional summary of the content)",
  "detailed_summary": "Detailed Summary (Generate an in-depth summary with all major points and timelines)",
  "minutes": "Meeting Minutes (Convert the dialogues/text into structured meeting minutes)",
  "actions": "Action Items (Extract action items, assignees if visible, and deadlines)",
  "mcqs": "MCQs (Generate Multiple Choice Questions based on the facts)",
  "faqs": "FAQs (Generate Frequently Asked Questions with answers)",
  "linkedin": "LinkedIn Post (Write a professional engaging LinkedIn post summarizing the content)",
  "twitter": "Twitter/X Thread (Write a multi-part Twitter thread)",
  "facebook": "Facebook Post (Write a community-focused Facebook post)",
  "instagram": "Instagram Caption (Write a visual-first Instagram caption with emojis)",
  "blog": "Professional Blog (Write a comprehensive blog post using the content)",
  "article": "Article (Draft a formal article with headings and structured paragraphs)",
  "press": "Press Release (Write a formal press release announcement)",
  "advisory": "Advisory (Generate a formal advisory notice or bulletin)",
  "research": "Research Summary (Generate an academic-style research summary)",
  "presentation": "Presentation (Structure the content as presentation slides)",
  "speaker_notes": "Presentation Speaker Notes (Draft notes for a speaker presenting this content)",
  "infographic_content": "Infographic Content (Extract key stats and facts for an infographic)",
  "infographic_layout": "Infographic Layout (Suggest a visual layout for the infographic)",
  "key_messages": "Key Messages (Extract the 3-5 absolute most important takeaways)",
  "video_script": "Video Script (Reformat the transcript into a polished script)",
  "storyboard": "Complete Storyboard (Generate a scene-by-scene storyboard with visual descriptions)",
  "scene_desc": "Scene Descriptions (Describe the physical scenes detected in the video)",
  "narration": "Narration Script (Draft a clean script for a voiceover narrator)",
  "voiceover": "Voice-over Script (Draft a voice-over script focusing on timing and pauses)",
  "subtitles": "Subtitles (.srt) (Generate SRT formatted subtitles with timestamps)",
  "captions": "Captions (.vtt) (Generate VTT formatted web captions)",
  "shot_list": "Shot List (Generate a camera shot list based on visual OCR/scenes)",
  "visual_recs": "Visual Recommendations (Suggest B-roll and visual assets)",
  "thumbnails": "Thumbnail Suggestions (Suggest 3 YouTube thumbnail ideas with text and imagery)",
  "social_package": "Social Media Package (Generate a bundled pack of tweets, posts, and captions)",
  "seo_title": "SEO Title (Generate 5 highly clickable SEO-optimized titles)",
  "seo_desc": "SEO Description (Generate an SEO meta description)",
  "hashtags": "Hashtags (Generate a list of 20 relevant hashtags)",
  "keywords": "Keywords (Extract primary and secondary SEO keywords)",
  "email": "Email Draft (Draft an email newsletter sharing this content)",
  "newsletter": "Newsletter (Write a full email newsletter edition)",
  "documentation": "Documentation (Generate technical documentation or a user manual)",
  "markdown": "Markdown (Format text into detailed clean Markdown with headings)",
  "json": "JSON (Extract all facts and structure them into a valid JSON object)",
  "csv": "CSV (Extract any tabular data or lists into comma-separated values format)",
  "txt": "TXT (Clean readable plain text alignment)",
  "pdf": "PDF Structure (Generate content optimized for a PDF report)",
  "docx": "DOCX Structure (Generate content optimized for a Word document)",
  "pptx": "PPTX Structure (Generate content strictly as slides)",
  "html": "HTML (Generate valid HTML5 semantic markup)",
  "xml": "XML (Extract facts into a valid XML tree)",
  "yaml": "YAML (Extract facts into valid YAML format)",
  "video_package": "Video Package (Generate a massive master document containing: Script, Storyboard, Scene Numbers, Camera Angles, Visual Descriptions, Actions, Background, Lighting, Music, Tone, Subtitles, Transitions, Editing Notes, B-roll, End Screen, CTA, and Image Prompts)",
  "resume": "Resume (Format the content into a professional CV or Resume structure)",
  "translation": "Translation (Translate the content to English if it is not, otherwise refine the translation)",
  "legal_simp": "Legal Simplification (Translate complex legal jargon into plain, easily understood language)",
  "medical_sum": "Medical Summary (Extract medical conditions, treatments, and advice into a structured summary)",
  "cyber_adv": "Cyber Advisory (Format the content as a cybersecurity threat advisory or incident report)",
};

export const presetOptions = [
  { id: "summary", label: "General Summary" },
  { id: "exec_summary", label: "Executive Summary" },
  { id: "detailed_summary", label: "Detailed Summary" },
  { id: "minutes", label: "Meeting Minutes" },
  { id: "actions", label: "Action Items" },
  { id: "mcqs", label: "MCQs (Quiz)" },
  { id: "faqs", label: "FAQs" },
  { id: "linkedin", label: "LinkedIn Post" },
  { id: "twitter", label: "Twitter/X Thread" },
  { id: "facebook", label: "Facebook Post" },
  { id: "instagram", label: "Instagram Caption" },
  { id: "blog", label: "Professional Blog" },
  { id: "article", label: "Article" },
  { id: "press", label: "Press Release" },
  { id: "advisory", label: "Advisory Bulletin" },
  { id: "research", label: "Research Summary" },
  { id: "presentation", label: "Presentation" },
  { id: "speaker_notes", label: "Speaker Notes" },
  { id: "infographic_content", label: "Infographic Content" },
  { id: "key_messages", label: "Key Messages" },
  { id: "video_script", label: "Video Script" },
  { id: "storyboard", label: "Storyboard" },
  { id: "narration", label: "Narration Script" },
  { id: "subtitles", label: "Subtitles (.srt)" },
  { id: "social_package", label: "Social Media Pack" },
  { id: "seo_title", label: "SEO Titles" },
  { id: "email", label: "Email Draft" },
  { id: "newsletter", label: "Newsletter" },
  { id: "documentation", label: "Documentation" },
  { id: "resume", label: "Resume / CV" },
  { id: "translation", label: "Translation" },
  { id: "legal_simp", label: "Legal Simplification" },
  { id: "medical_sum", label: "Medical Summary" },
  { id: "cyber_adv", label: "Cyber Advisory" },
  { id: "markdown", label: "Markdown" },
  { id: "json", label: "JSON" },
  { id: "csv", label: "CSV" },
  { id: "txt", label: "TXT" },
  { id: "pdf", label: "PDF" },
  { id: "docx", label: "DOCX" },
  { id: "pptx", label: "PPTX" },
  { id: "html", label: "HTML" },
  { id: "xml", label: "XML" },
  { id: "yaml", label: "YAML" },
  { id: "video_package", label: "Video Package (Full)" }
];
